name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 2.4.0
homepage: https://pub.dev/packages/flutter_stripe
repository: https://github.com/icoffee-app/flutter_stripe

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  stripe_ios:
    path: ../stripe_ios
  stripe_platform_interface:
    path: ../stripe_platform_interface
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4



